### ISSUE TITLE
If output directory does not already exist, parallel_bundle_adjust fails

### ISSUE THREAD

**Issue by otherorb** [NeoGeographyToolkit/StereoPipeline#425]
**Describe the bug**
When running parallel_bundle_adjust, if the directory specified by '-o dir/run' does not already exist, parallel bundle adjust's python module will fail:
 
Traceback (most recent call last):
  File "/home/moses/Work/ASP/libexec/parallel_bundle_adjust", line 429, in <module>
    shutil.copy2(opt.nodes_list, local_nodes_list)
  File "/home/moses/Work/ASP/lib/python3.12/shutil.py", line 463, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/moses/Work/ASP/lib/python3.12/shutil.py", line 262, in copyfile
    with open(dst, 'wb') as fdst:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'ba0/run-nodes-list.txt'

This is new behavior with 16 Feb 2024 daily build.

**Comment by oleg-alexandrov** [comment]
That was on oversight. I put a fix. Will be in tomorrow's build. Thanks for noticing.
